name = "Ada-Fuse"
version = "1.0.0"
description = "Ada bindings for Fuse (Filesystem in Userspace)"
website = "https://github.com/medsec/ada-fuse"
authors  = [
    "Alexander Herr <thissideup@riseup.net>",
    "Nicolai Ruckel <nicolai.ruckel@uni-weimar.de>",
    "Christopher Lübbemeier <christopher.luebbemeier@googlemail.com>"
    ]
maintainers = ["Nicolai Ruckel <nicolai.ruckel@uni-weimar.de>"]
maintainers-logins = [
    "NicolaiRuckel", "medsec"
]
licenses = ["GPL 3.0"]
project-files = ["ada_fuse.gpr"]

[gpr-externals]
ADA_FUSE_SYSTEM = ["Linux x86_64", "Linux i386", "Darwin i386", "Darwin x86_64"]

[gpr-set-externals.'case(os)']
linux = { ADA_FUSE_SYSTEM = "Linux x86_64" }
macos = { ADA_FUSE_SYSTEM = "Darwin x86_64" }

[available.'case(os)']
linux   = true
macos   = true
windows = false
'...'   = false

[origin]
url = "git+https://github.com/medsec/ada-fuse"
commit = "af2d0ac124289f39cf0d5361f01bab445f165911"

[origin.depends-on]
libfuse = "^2.0.0"
