#!/usr/bin/env python3
import subprocess
from os.path import *
import shutil
OPTION="""   pragma Linker_Options ("%(name)s");"""
TEMPLATE="""private package Fuse.Libfuse is
%(options)s
end fuse.Libfuse;"""

make_dir = dirname(shutil.which("make"))
pkg_config_dir = dirname(shutil.which("pkg-config"))
gprbuild_dir = dirname(shutil.which("gprbuild"))
if gprbuild_dir == make_dir:
    pkg_config = "pkg-config"
else:
    pkg_config = join(make_dir,"pkg-config")
options=[]
for i in subprocess.check_output([pkg_config,"--libs","fuse"]).decode("utf-8").strip().split():
    options.append(OPTION % {"name":i})
    
with open("src/fuse-libfuse.ads","w") as outf:
    outf.write (TEMPLATE % {"options":"\n".join(options)})
